### ISSUE TITLE
Add .gitignore file and remove node_modules directory

### ISSUE THREAD

**Issue by huynhsamha** [Aleadinglight/Express-demo#1]
You should remove `node_modules` directory from your repository and add `.gitignore` file at the root with the content as the following file [https://github.com/github/gitignore/blob/master/Node.gitignore](https://github.com/github/gitignore/blob/master/Node.gitignore)

--
:+1:  hehe - issue to my friend @Aleadinglight :+1:

**Comment by Aleadinglight** [comment]
And why should I do that, my friend?

**Comment by huynhsamha** [comment]
When I clone your repository, I dont need `node_modules` directory. File `package.json` has information about packages used in the project. I only run `npm install`, the `node_modules` will be generated. So it should be ignored by git which is added to `.gitignore`

**Comment by Aleadinglight** [comment]
Fixed.
